/* PORT-M3 -- compile-time type check of the game's callback tables.
 *
 * Every slot below is given the function-pointer type its CALL SITE uses,
 * and every body registered into that slot is declared with the signature
 * its DEFINITION really has (both printed from the same wasm-signature ->
 * C mapping: i32 -> void*, f32 -> float). An initialiser therefore compiles
 * only when the two are the SAME wasm type -- which is exactly the
 * condition for `call_indirect` through that slot not to trap.
 *
 * Generated by the lane's census (see docs/lanes/scope-port-m3.md section 1)
 * from the real signatures in the wasm objects. Regenerate after changing a
 * callback's shape; do not hand-edit the tables.
 *
 * Build (no link needed -- the check is the compile):
 *   emcc -c -Wall -Werror=incompatible-function-pointer-types \
 *        portable/tests/test_callback_types.c -o /tmp/cbtypes.o
 *
 * Bodies that do NOT have their slot's type are listed in the comment at
 * the end of each group: those reach the slot through a PORT-M3 adapter
 * (registration-site static, see the registering file) and so cannot be
 * named here.
 */

#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic error "-Wincompatible-function-pointer-types"
#endif

/* ---- cb_90
 * call site: ObjDef +0x90  eventtick.c:400, gameframe.c:991, mappath.c:585, objmap2.c:556, objrect.c:385, workorder2.c:1018
 * type:      (i32, i32, i32) -> void  */
extern void BoatingSchool_Update(void*, void*, void*);
extern void BsWater_CalcCursor(void*, void*, void*);
extern void CrocodileFountain_Update(void*, void*, void*);
extern void CtThunk_Update(void*, void*, void*);
extern void DrivingSchool_Update(void*, void*, void*);
extern void ElephantFountain_Update(void*, void*, void*);
extern void JcWater_CalcCursor(void*, void*, void*);
extern void JungleCruise_Update(void*, void*, void*);
extern void LFCorner1_Update(void*, void*, void*);
extern void LFCorner2_Update(void*, void*, void*);
extern void LFCorner3_Update(void*, void*, void*);
extern void LFCorner4_Update(void*, void*, void*);
extern void LFCsaw_Update(void*, void*, void*);
extern void LFDrop_Update(void*, void*, void*);
extern void LFEntrance_Update(void*, void*, void*);
extern void LFHoldUp_Update(void*, void*, void*);
extern void LFTrack_Update(void*, void*, void*);
extern void LFTunnel_Update(void*, void*, void*);
extern void Mermaid_CalcCursor(void*, void*, void*);
extern void MonkeyFish_CalcCursor(void*, void*, void*);
extern void MonkeyTree_CalcCursor(void*, void*, void*);
extern void Pump_Update(void*, void*, void*);
extern void Roads_CalcCursor(void*, void*, void*);
extern void Shower_Update(void*, void*, void*);
extern void WaterBlock_Update(void*, void*, void*);
extern void ZebraCrossing_Update(void*, void*, void*);

typedef void (*ll_fn_cb_90)(void*, void*, void*);
ll_fn_cb_90 const ll_tab_cb_90[] = {
    BoatingSchool_Update,
    BsWater_CalcCursor,
    CrocodileFountain_Update,
    CtThunk_Update,
    DrivingSchool_Update,
    ElephantFountain_Update,
    JcWater_CalcCursor,
    JungleCruise_Update,
    LFCorner1_Update,
    LFCorner2_Update,
    LFCorner3_Update,
    LFCorner4_Update,
    LFCsaw_Update,
    LFDrop_Update,
    LFEntrance_Update,
    LFHoldUp_Update,
    LFTrack_Update,
    LFTunnel_Update,
    Mermaid_CalcCursor,
    MonkeyFish_CalcCursor,
    MonkeyTree_CalcCursor,
    Pump_Update,
    Roads_CalcCursor,
    Shower_Update,
    WaterBlock_Update,
    ZebraCrossing_Update,
};
/* not named above, and why:
 *   Track_Update90  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 */

/* ---- cb_94
 * call site: ObjDef +0x94  gameframe.c:958, eventtick.c:511, mappath.c:478, fpui3.c:295, misc3.c:700
 * type:      (i32, i32) -> void  */
extern void BoatingSchool_DrawSelection(void*, void*);
extern void BsWater_DrawSelection(void*, void*);
extern void CtThunk_Update2(void*, void*);
extern void DrivingSchool_DrawSelection(void*, void*);
extern void JcWater_DrawSelection(void*, void*);
extern void JungleCruiseMonkeyFish_DrawSelection(void*, void*);
extern void JungleCruiseMonkeyTree_DrawSelection(void*, void*);
extern void JungleCruise_DrawSelection(void*, void*);
extern void LFCorner1_Update2(void*, void*);
extern void LFCorner2_Update2(void*, void*);
extern void LFCorner3_Update2(void*, void*);
extern void LFCorner4_Update2(void*, void*);
extern void LFCsaw_Update2(void*, void*);
extern void LFDrop_Update2(void*, void*);
extern void LFEntrance_Update2(void*, void*);
extern void LFHoldUp_Update2(void*, void*);
extern void LFTrack_Update2(void*, void*);
extern void LFTunnel_Update2(void*, void*);
extern void Mermaid_CalcCursor2(void*, void*);
extern void Road_DrawSelection(void*, void*);

typedef void (*ll_fn_cb_94)(void*, void*);
ll_fn_cb_94 const ll_tab_cb_94[] = {
    BoatingSchool_DrawSelection,
    BsWater_DrawSelection,
    CtThunk_Update2,
    DrivingSchool_DrawSelection,
    JcWater_DrawSelection,
    JungleCruiseMonkeyFish_DrawSelection,
    JungleCruiseMonkeyTree_DrawSelection,
    JungleCruise_DrawSelection,
    LFCorner1_Update2,
    LFCorner2_Update2,
    LFCorner3_Update2,
    LFCorner4_Update2,
    LFCsaw_Update2,
    LFDrop_Update2,
    LFEntrance_Update2,
    LFHoldUp_Update2,
    LFTrack_Update2,
    LFTunnel_Update2,
    Mermaid_CalcCursor2,
    Road_DrawSelection,
};

/* ---- cb_remove
 * call site: ObjDef +0x9c  objmap2.c:1895
 * type:      (i32, i32, i32) -> void  */
extern void Balloonz_Remove(void*, void*, void*);
extern void BoatingSchoolWater_Remove(void*, void*, void*);
extern void BoatingSchool_Remove(void*, void*, void*);
extern void BsMermaid_Remove(void*, void*, void*);
extern void Carousel_Remove(void*, void*, void*);
extern void CastleBbq_Remove(void*, void*, void*);
extern void CastleLevel1_Remove(void*, void*, void*);
extern void Catapult_Remove(void*, void*, void*);
extern void Copters_Remove(void*, void*, void*);
extern void CrocodileFountain_Remove(void*, void*, void*);
extern void CtThunk_Remove(void*, void*, void*);
extern void DrivingSchool_Remove(void*, void*, void*);
extern void EarthSlide_Remove(void*, void*, void*);
extern void ElephantFountain_Remove(void*, void*, void*);
extern void Entrance1_Remove(void*, void*, void*);
extern void FoodService_Remove(void*, void*, void*);
extern void Fort_Remove(void*, void*, void*);
extern void GoldRush_Remove(void*, void*, void*);
extern void Hedge_Remove(void*, void*, void*);
extern void JailCell_Remove(void*, void*, void*);
extern void Joust_Remove(void*, void*, void*);
extern void JungleCruiseWater_Remove(void*, void*, void*);
extern void JungleCruise_Remove(void*, void*, void*);
extern void LFCorner1_Remove(void*, void*, void*);
extern void LFCorner2_Remove(void*, void*, void*);
extern void LFCorner3_Remove(void*, void*, void*);
extern void LFCorner4_Remove(void*, void*, void*);
extern void LFCsaw_Remove(void*, void*, void*);
extern void LFDrop_Remove(void*, void*, void*);
extern void LFEntrance_Remove(void*, void*, void*);
extern void LFHoldUp_Remove(void*, void*, void*);
extern void LFTrack_Remove(void*, void*, void*);
extern void LFTunnel_Remove(void*, void*, void*);
extern void LegoShop1_Remove(void*, void*, void*);
extern void MechanicsHut_Remove(void*, void*, void*);
extern void MonkeyFish_Remove(void*, void*, void*);
extern void MonkeyTree_Remove(void*, void*, void*);
extern void PlaneRide_Remove(void*, void*, void*);
extern void PottingShed_Remove(void*, void*, void*);
extern void Pumps_Remove(void*, void*, void*);
extern void RemoveBasicPath(void*, void*, void*);
extern void RemoveSoundObject(void*, void*, void*);
extern void Restaurant1_Remove(void*, void*, void*);
extern void Restaurant2_Remove(void*, void*, void*);
extern void Roads_Remove(void*, void*, void*);
extern void SafariRide_Remove(void*, void*, void*);
extern void Shop_Remove(void*, void*, void*);
extern void Shower_Remove(void*, void*, void*);
extern void SpaceTower_Remove(void*, void*, void*);
extern void SpiderRide_Remove(void*, void*, void*);
extern void SpinningBarrels_Remove(void*, void*, void*);
extern void TempleSlide_Remove(void*, void*, void*);
extern void Temple_Remove(void*, void*, void*);
extern void WWEntrance_Remove(void*, void*, void*);
extern void WaterBlock_Remove(void*, void*, void*);

typedef void (*ll_fn_cb_remove)(void*, void*, void*);
ll_fn_cb_remove const ll_tab_cb_remove[] = {
    Balloonz_Remove,
    BoatingSchoolWater_Remove,
    BoatingSchool_Remove,
    BsMermaid_Remove,
    Carousel_Remove,
    CastleBbq_Remove,
    CastleLevel1_Remove,
    Catapult_Remove,
    Copters_Remove,
    CrocodileFountain_Remove,
    CtThunk_Remove,
    DrivingSchool_Remove,
    EarthSlide_Remove,
    ElephantFountain_Remove,
    Entrance1_Remove,
    FoodService_Remove,
    Fort_Remove,
    GoldRush_Remove,
    Hedge_Remove,
    JailCell_Remove,
    Joust_Remove,
    JungleCruiseWater_Remove,
    JungleCruise_Remove,
    LFCorner1_Remove,
    LFCorner2_Remove,
    LFCorner3_Remove,
    LFCorner4_Remove,
    LFCsaw_Remove,
    LFDrop_Remove,
    LFEntrance_Remove,
    LFHoldUp_Remove,
    LFTrack_Remove,
    LFTunnel_Remove,
    LegoShop1_Remove,
    MechanicsHut_Remove,
    MonkeyFish_Remove,
    MonkeyTree_Remove,
    PlaneRide_Remove,
    PottingShed_Remove,
    Pumps_Remove,
    RemoveBasicPath,
    RemoveSoundObject,
    Restaurant1_Remove,
    Restaurant2_Remove,
    Roads_Remove,
    SafariRide_Remove,
    Shop_Remove,
    Shower_Remove,
    SpaceTower_Remove,
    SpiderRide_Remove,
    SpinningBarrels_Remove,
    TempleSlide_Remove,
    Temple_Remove,
    WWEntrance_Remove,
    WaterBlock_Remove,
};
/* not named above, and why:
 *   MediaShop_Remove  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 */

/* ---- cb_a0
 * call site: ObjDef +0xa0  renderview.c:1221
 * type:      (i32, i32) -> i32  */
extern int Balloonz_GetDrawDesc(void*, void*);
extern int Brolly_GetDrawDesc(void*, void*);
extern int Carousel_GetDrawDesc(void*, void*);
extern int DrivingSchool_GetDrawDesc(void*, void*);
extern int JcMonkeyFish_GetDrawDesc(void*, void*);
extern int JcMonkeyTree_GetDrawDesc(void*, void*);
extern int MechanicsHut_GetDrawDesc(void*, void*);
extern int PottingShed_GetDrawDesc(void*, void*);
extern int Restaurant2_GetDrawDesc(void*, void*);

typedef int (*ll_fn_cb_a0)(void*, void*);
ll_fn_cb_a0 const ll_tab_cb_a0[] = {
    Balloonz_GetDrawDesc,
    Brolly_GetDrawDesc,
    Carousel_GetDrawDesc,
    DrivingSchool_GetDrawDesc,
    JcMonkeyFish_GetDrawDesc,
    JcMonkeyTree_GetDrawDesc,
    MechanicsHut_GetDrawDesc,
    PottingShed_GetDrawDesc,
    Restaurant2_GetDrawDesc,
};
/* not named above, and why:
 *   DrawBasicPath  [(i32, i32, i32, i32) -> void]
 *   Joust_A0  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   TempleSlide_A0  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 */

/* ---- cb_a4
 * call site: ObjDef +0xa4  llidb_odf.c:281
 * type:      (i32) -> void  */
extern void Balloonz_Create(void*);
extern void BoatingSchool_Create(void*);
extern void Brolly_LoadResources(void*);
extern void BsWater_LoadResources(void*);
extern void Carousel_Create(void*);
extern void CastleBbq_LoadResources(void*);
extern void CastleDummy_Create(void*);
extern void Castle_Create(void*);
extern void ChuckWagon_LoadResources(void*);
extern void DrivingSchool_Create(void*);
extern void EarthSlide_Create(void*);
extern void Entrance1_Create(void*);
extern void FoodcartDrink_LoadResources(void*);
extern void FoodcartFood_LoadResources(void*);
extern void FoodcartIcecream_LoadResources(void*);
extern void JcMonkeyFish_Create(void*);
extern void JcMonkeyTree_Create(void*);
extern void JungleCruiseWater_Create(void*);
extern void JungleCruise_Create(void*);
extern void MechanicsHut_Create(void*);
extern void Mermaid_LoadResources(void*);
extern void OctopusCafe_Create(void*);
extern void PottingShed_Create(void*);
extern void Pump_LoadResources(void*);
extern void Restaurant1_Create(void*);
extern void Restaurant2_Create(void*);
extern void Roads_LoadResources(void*);
extern void SharkCafe_LoadResources(void*);
extern void TrackH0_Create(void*);
extern void TrackHP_Create(void*);
extern void TrackH_Create(void*);
extern void Track_Create(void*);
extern void ZebraCrossing_LoadResources(void*);

typedef void (*ll_fn_cb_a4)(void*);
ll_fn_cb_a4 const ll_tab_cb_a4[] = {
    Balloonz_Create,
    BoatingSchool_Create,
    Brolly_LoadResources,
    BsWater_LoadResources,
    Carousel_Create,
    CastleBbq_LoadResources,
    CastleDummy_Create,
    Castle_Create,
    ChuckWagon_LoadResources,
    DrivingSchool_Create,
    EarthSlide_Create,
    Entrance1_Create,
    FoodcartDrink_LoadResources,
    FoodcartFood_LoadResources,
    FoodcartIcecream_LoadResources,
    JcMonkeyFish_Create,
    JcMonkeyTree_Create,
    JungleCruiseWater_Create,
    JungleCruise_Create,
    MechanicsHut_Create,
    Mermaid_LoadResources,
    OctopusCafe_Create,
    PottingShed_Create,
    Pump_LoadResources,
    Restaurant1_Create,
    Restaurant2_Create,
    Roads_LoadResources,
    SharkCafe_LoadResources,
    TrackH0_Create,
    TrackHP_Create,
    TrackH_Create,
    Track_Create,
    ZebraCrossing_LoadResources,
};
/* not named above, and why:
 *   Joust_A4  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   TempleSlide_A4  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 */

/* ---- cb_a8
 * call site: ObjDef +0xa8  renderview.c:1130
 * type:      (i32) -> void  */
extern void Balloonz_Tick(void*);
extern void Carousel_Tick(void*);
extern void CastleBbq_Tick(void*);
extern void Castle_Activate(void*);
extern void ChuckWagon_TickCustomers(void*);
extern void DrivingSchool_TickRiders(void*);
extern void EarthSlide_Tick(void*);
extern void Entrance1_Tick(void*);
extern void FoodcartDrink_Tick(void*);
extern void FoodcartFood_Tick(void*);
extern void FoodcartIcecream_Tick(void*);
extern void Joust_Update(void*);
extern void MechanicsHut_Tick(void*);
extern void OctopusCafe_Tick(void*);
extern void PottingShed_Tick(void*);
extern void Restaurant1_Tick(void*);
extern void Restaurant2_Tick(void*);
extern void SharkCafe_Tick(void*);

typedef void (*ll_fn_cb_a8)(void*);
ll_fn_cb_a8 const ll_tab_cb_a8[] = {
    Balloonz_Tick,
    Carousel_Tick,
    CastleBbq_Tick,
    Castle_Activate,
    ChuckWagon_TickCustomers,
    DrivingSchool_TickRiders,
    EarthSlide_Tick,
    Entrance1_Tick,
    FoodcartDrink_Tick,
    FoodcartFood_Tick,
    FoodcartIcecream_Tick,
    Joust_Update,
    MechanicsHut_Tick,
    OctopusCafe_Tick,
    PottingShed_Tick,
    Restaurant1_Tick,
    Restaurant2_Tick,
    SharkCafe_Tick,
};
/* not named above, and why:
 *   BoatingSchool_Tick  [() -> void]
 *   JungleCruise_Tick  [() -> void]
 *   TempleSlide_A8  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 */

/* ---- cb_ac
 * call site: ObjDef +0xac  sysmisc.c:664
 * type:      (i32) -> void  */
extern void BoatingSchool_Destroy(void*);
extern void Carousel_Destroy(void*);
extern void DrivingSchool_Destroy(void*);
extern void EarthSlide_FreeResources(void*);
extern void Entrance1_Destroy(void*);
extern void JungleCruise_Destroy(void*);
extern void Track_Destroy(void*);

typedef void (*ll_fn_cb_ac)(void*);
ll_fn_cb_ac const ll_tab_cb_ac[] = {
    BoatingSchool_Destroy,
    Carousel_Destroy,
    DrivingSchool_Destroy,
    EarthSlide_FreeResources,
    Entrance1_Destroy,
    JungleCruise_Destroy,
    Track_Destroy,
};
/* not named above, and why:
 *   Balloonz_Destroy  [() -> void]
 *   Brolly_FreeResources  [() -> void]
 *   CastleBbq_FreeResources  [() -> void]
 *   Castle_Destroy  [() -> void]
 *   ChuckWagon_FreeResources  [() -> void]
 *   Dino_AC  [() -> void]
 *   FoodcartDrink_FreeResources  [() -> void]
 *   FoodcartFood_FreeResources  [() -> void]
 *   FoodcartIcecream_FreeResources  [() -> void]
 *   Fountain_AC  [() -> void]
 *   Joust_AC  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   JungleCruiseMonkeyFish_Destroy  [() -> void]
 *   JungleCruiseMonkeyTree_Destroy  [() -> void]
 *   MechanicsHut_Destroy  [() -> void]
 *   OctopusCafe_Destroy  [() -> void]
 *   PottingShed_Destroy  [() -> void]
 *   PowerStation_AC  [() -> void]
 *   Restaurant1_FreeResources  [() -> void]
 *   Restaurant2_Destroy  [() -> void]
 *   Roads_FreeResources  [() -> void]
 *   SharkCafe_FreeResources  [() -> void]
 *   TempleSlide_AC  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 */

/* ---- cb_load
 * call site: ObjDef +0xb8  savegame.c:1365
 * type:      (i32) -> i32  */
extern int Balloonz_Load(void*);
extern int Carousel_Load(void*);
extern int LoadJoust(void*);
extern int LoadSafariRide(void*);
extern int LoadTempleSlide(void*);

typedef int (*ll_fn_cb_load)(void*);
ll_fn_cb_load const ll_tab_cb_load[] = {
    Balloonz_Load,
    Carousel_Load,
    LoadJoust,
    LoadSafariRide,
    LoadTempleSlide,
};
/* not named above, and why:
 *   EarthSlide_Load  [() -> i32]
 *   LoadBoatingSchool  [() -> i32]
 *   LoadCatapult  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   LoadCopters  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   LoadDrivingSchool  [() -> i32]
 *   LoadElephantFountain  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   LoadGoldWash  [() -> i32]
 *   LoadJailCells  [() -> i32]
 *   LoadJungleCruise  [() -> i32]
 *   LoadLogFlume  [() -> i32]
 *   LoadPlaneRide  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   LoadRollerCoaster  [() -> i32]
 *   LoadSpaceTower  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   LoadSpiderRide  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   LoadSpinningBarrels  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   LoadWaterBlock  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   Restaurant1_Load  [() -> i32]
 *   Restaurant2_Load  [() -> i32]
 */

/* ---- cb_c0
 * call site: ObjDef +0xc0  appraisal.c:172, eventtick2.c:232
 * type:      (i32, i32) -> i32  */
extern int BoatingSchool_BestTake(void*, void*);
extern int Castle_Extra(void*, void*);
extern int DrivingSchool_BestTake(void*, void*);
extern int JungleCruise_BestValue(void*, void*);
extern int LFEntrance_Extra(void*, void*);

typedef int (*ll_fn_cb_c0)(void*, void*);
ll_fn_cb_c0 const ll_tab_cb_c0[] = {
    BoatingSchool_BestTake,
    Castle_Extra,
    DrivingSchool_BestTake,
    JungleCruise_BestValue,
    LFEntrance_Extra,
};

/* ---- input
 * call site: Icon +0x2c   fpui.c:774/777, uimisc.c:607, and g_icon_handler1/2 at fpui.c:768/787
 * type:      (i32, i32, i32, i32) -> i32  */
extern int AdventureThemeInput(void*, void*, void*, void*);
extern int AdvertBillundInput(void*, void*, void*, void*);
extern int AdvertCaliforniaInput(void*, void*, void*, void*);
extern int AdvertGoBackInput(void*, void*, void*, void*);
extern int AdvertWindsorInput(void*, void*, void*, void*);
extern int BriefIconInput(void*, void*, void*, void*);
extern int CastleThemeInput(void*, void*, void*, void*);
extern int CertGoBackInput(void*, void*, void*, void*);
extern int CertPrintInput(void*, void*, void*, void*);
extern int ChildrenBarInput(void*, void*, void*, void*);
extern int CloseChildrenBarInput(void*, void*, void*, void*);
extern int DeleteIconInput(void*, void*, void*, void*);
extern int EraserIconInput(void*, void*, void*, void*);
extern int ExitCloseInput(void*, void*, void*, void*);
extern int FreePlayAcceptInput(void*, void*, void*, void*);
extern int FreePlayGoBackInput(void*, void*, void*, void*);
extern int IndicatorInput(void*, void*, void*, void*);
extern int LegolandThemeInput(void*, void*, void*, void*);
extern int LoadAcceptInput(void*, void*, void*, void*);
extern int LowProgressAcceptInput(void*, void*, void*, void*);
extern int MapIconInput(void*, void*, void*, void*);
extern int NewProfileCloseInput(void*, void*, void*, void*);
extern int OptionAcceptInput(void*, void*, void*, void*);
extern int OptionLoadInput(void*, void*, void*, void*);
extern int OptionSaveInput(void*, void*, void*, void*);
extern int OptionsIconInput(void*, void*, void*, void*);
extern int PU_CloseInput(void*, void*, void*, void*);
extern int PU_Delete2Input(void*, void*, void*, void*);
extern int PU_DeleteInput(void*, void*, void*, void*);
extern int PU_GardenerInput(void*, void*, void*, void*);
extern int PU_MechInput(void*, void*, void*, void*);
extern int PU_NextInput(void*, void*, void*, void*);
extern int PU_PrevInput(void*, void*, void*, void*);
extern int PathIconInput(void*, void*, void*, void*);
extern int ProfileAcceptInput(void*, void*, void*, void*);
extern int ProfileCloseInput(void*, void*, void*, void*);
extern int ProfileEmptySlotInput(void*, void*, void*, void*);
extern int ProfileOkInput(void*, void*, void*, void*);
extern int ProfileSlotInput(void*, void*, void*, void*);
extern int ProgressAcceptInput(void*, void*, void*, void*);
extern int ProgressGoBackInput(void*, void*, void*, void*);
extern int ProgressLevelInput(void*, void*, void*, void*);
extern int ProgressTutorialInput(void*, void*, void*, void*);
extern int QueryIconInput(void*, void*, void*, void*);
extern int ReportAcceptInput(void*, void*, void*, void*);
extern int ReportHintInput(void*, void*, void*, void*);
extern int ReportNextPageInput(void*, void*, void*, void*);
extern int ReportPrevPageInput(void*, void*, void*, void*);
extern int SaveAcceptInput(void*, void*, void*, void*);
extern int SaveDeleteOkInput(void*, void*, void*, void*);
extern int SaveEmptySlotInput(void*, void*, void*, void*);
extern int SaveGameCloseInput(void*, void*, void*, void*);
extern int SaveGameOkInput(void*, void*, void*, void*);
extern int SaveGoBackInput(void*, void*, void*, void*);
extern int SaveScreenAcceptInput(void*, void*, void*, void*);
extern int SaveSlotInput(void*, void*, void*, void*);
extern int ScriptEndActiveInput(void*, void*, void*, void*);
extern int ScriptEndIconInput(void*, void*, void*, void*);
extern int ScrollDownInput(void*, void*, void*, void*);
extern int ScrollUpInput(void*, void*, void*, void*);
extern int TitleExitInput(void*, void*, void*, void*);
extern int TitleFreeInput(void*, void*, void*, void*);
extern int TitleLoadInput(void*, void*, void*, void*);
extern int TitleMovieInput(void*, void*, void*, void*);
extern int TitleNewInput(void*, void*, void*, void*);
extern int TitleRegInput(void*, void*, void*, void*);
extern int VolDownInput(void*, void*, void*, void*);
extern int VolMarkerInput(void*, void*, void*, void*);
extern int VolUpInput(void*, void*, void*, void*);
extern int WesternThemeInput(void*, void*, void*, void*);

typedef int (*ll_fn_input)(void*, void*, void*, void*);
ll_fn_input const ll_tab_input[] = {
    AdventureThemeInput,
    AdvertBillundInput,
    AdvertCaliforniaInput,
    AdvertGoBackInput,
    AdvertWindsorInput,
    BriefIconInput,
    CastleThemeInput,
    CertGoBackInput,
    CertPrintInput,
    ChildrenBarInput,
    CloseChildrenBarInput,
    DeleteIconInput,
    EraserIconInput,
    ExitCloseInput,
    FreePlayAcceptInput,
    FreePlayGoBackInput,
    IndicatorInput,
    LegolandThemeInput,
    LoadAcceptInput,
    LowProgressAcceptInput,
    MapIconInput,
    NewProfileCloseInput,
    OptionAcceptInput,
    OptionLoadInput,
    OptionSaveInput,
    OptionsIconInput,
    PU_CloseInput,
    PU_Delete2Input,
    PU_DeleteInput,
    PU_GardenerInput,
    PU_MechInput,
    PU_NextInput,
    PU_PrevInput,
    PathIconInput,
    ProfileAcceptInput,
    ProfileCloseInput,
    ProfileEmptySlotInput,
    ProfileOkInput,
    ProfileSlotInput,
    ProgressAcceptInput,
    ProgressGoBackInput,
    ProgressLevelInput,
    ProgressTutorialInput,
    QueryIconInput,
    ReportAcceptInput,
    ReportHintInput,
    ReportNextPageInput,
    ReportPrevPageInput,
    SaveAcceptInput,
    SaveDeleteOkInput,
    SaveEmptySlotInput,
    SaveGameCloseInput,
    SaveGameOkInput,
    SaveGoBackInput,
    SaveScreenAcceptInput,
    SaveSlotInput,
    ScriptEndActiveInput,
    ScriptEndIconInput,
    ScrollDownInput,
    ScrollUpInput,
    TitleExitInput,
    TitleFreeInput,
    TitleLoadInput,
    TitleMovieInput,
    TitleNewInput,
    TitleRegInput,
    VolDownInput,
    VolMarkerInput,
    VolUpInput,
    WesternThemeInput,
};
/* not named above, and why:
 *   close_fn  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   g_group_cb2  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   g_icon_handler1  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   ok_fn  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 */

/* ---- render
 * call site: Icon +0x28   fpui.c:671/705/739, popupmisc.c:459
 * type:      (i32) -> i32  */
extern int RenderBoxIcon(void*);
extern int RenderBriefIcon(void*);
extern int RenderClippedClassIcon(void*);
extern int RenderDarkTitleIcon(void*);
extern int RenderEnergyBar(void*);
extern int RenderFlashingSpriteIcon(void*);
extern int RenderFreePlayBar(void*);
extern int RenderFullScreenIcon(void*);
extern int RenderGBarSprite(void*);
extern int RenderGBarSpriteIcon(void*);
extern int RenderIndicatorIcon(void*);
extern int RenderLabelledIcon(void*);
extern int RenderMoneyBar(void*);
extern int RenderScroll_Icons(void*);

typedef int (*ll_fn_render)(void*);
ll_fn_render const ll_tab_render[] = {
    RenderBoxIcon,
    RenderBriefIcon,
    RenderClippedClassIcon,
    RenderDarkTitleIcon,
    RenderEnergyBar,
    RenderFlashingSpriteIcon,
    RenderFreePlayBar,
    RenderFullScreenIcon,
    RenderGBarSprite,
    RenderGBarSpriteIcon,
    RenderIndicatorIcon,
    RenderLabelledIcon,
    RenderMoneyBar,
    RenderScroll_Icons,
};
/* not named above, and why:
 *   RenderScriptEndIcon  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 */

/* ---- g_event_tick
 * call site: the per-kind script event handlers, fpui3.c:657
 * type:      (i32) -> i32  */
extern int EventTick_Addbricks(void*);
extern int EventTick_Addflag(void*);
extern int EventTick_Breifingfile_Briefingfile(void*);
extern int EventTick_Bridges(void*);
extern int EventTick_Capacity(void*);
extern int EventTick_Capacitycap(void*);
extern int EventTick_Capacityscale(void*);
extern int EventTick_Checkflag(void*);
extern int EventTick_Clear(void*);
extern int EventTick_Cleararea(void*);
extern int EventTick_Composite(void*);
extern int EventTick_Connect(void*);
extern int EventTick_Currency(void*);
extern int EventTick_Degrade(void*);
extern int EventTick_Endlevel(void*);
extern int EventTick_Entrancefee(void*);
extern int EventTick_Extendpark(void*);
extern int EventTick_Feature(void*);
extern int EventTick_Fixrides(void*);
extern int EventTick_Flashbutton(void*);
extern int EventTick_Fmv(void*);
extern int EventTick_Foodcoverage(void*);
extern int EventTick_Forever(void*);
extern int EventTick_Gardener_Mechanic(void*);
extern int EventTick_Give(void*);
extern int EventTick_Glue(void*);
extern int EventTick_Happiness(void*);
extern int EventTick_Hintsfile(void*);
extern int EventTick_Hunger(void*);
extern int EventTick_Interval(void*);
extern int EventTick_Kind3(void*);
extern int EventTick_Kind54(void*);
extern int EventTick_Kind68(void*);
extern int EventTick_Link(void*);
extern int EventTick_Lookat(void*);
extern int EventTick_Loopcomposite(void*);
extern int EventTick_Message(void*);
extern int EventTick_Need(void*);
extern int EventTick_Needat(void*);
extern int EventTick_Needgardeners(void*);
extern int EventTick_Needin(void*);
extern int EventTick_Needmechanics(void*);
extern int EventTick_Parkvisitors(void*);
extern int EventTick_Pathscenery(void*);
extern int EventTick_Place(void*);
extern int EventTick_Powerrides(void*);
extern int EventTick_Purge(void*);
extern int EventTick_Range(void*);
extern int EventTick_Remove(void*);
extern int EventTick_Removerange(void*);
extern int EventTick_Report(void*);
extern int EventTick_Ridecoverage(void*);
extern int EventTick_Riders(void*);
extern int EventTick_Ridevisitors(void*);
extern int EventTick_Save(void*);
extern int EventTick_Scenerycoverage(void*);
extern int EventTick_Selectmode(void*);
extern int EventTick_Selecttab(void*);
extern int EventTick_Selecttheme(void*);
extern int EventTick_Shopcoverage(void*);
extern int EventTick_Studarea(void*);
extern int EventTick_Take(void*);
extern int EventTick_Techlevel(void*);
extern int EventTick_Themeicon(void*);
extern int EventTick_Totcoverage(void*);
extern int EventTick_Unglue(void*);
extern int EventTick_Workers(void*);
extern int EventTick_Zoning(void*);

typedef int (*ll_fn_g_event_tick)(void*);
ll_fn_g_event_tick const ll_tab_g_event_tick[] = {
    EventTick_Addbricks,
    EventTick_Addflag,
    EventTick_Breifingfile_Briefingfile,
    EventTick_Bridges,
    EventTick_Capacity,
    EventTick_Capacitycap,
    EventTick_Capacityscale,
    EventTick_Checkflag,
    EventTick_Clear,
    EventTick_Cleararea,
    EventTick_Composite,
    EventTick_Connect,
    EventTick_Currency,
    EventTick_Degrade,
    EventTick_Endlevel,
    EventTick_Entrancefee,
    EventTick_Extendpark,
    EventTick_Feature,
    EventTick_Fixrides,
    EventTick_Flashbutton,
    EventTick_Fmv,
    EventTick_Foodcoverage,
    EventTick_Forever,
    EventTick_Gardener_Mechanic,
    EventTick_Give,
    EventTick_Glue,
    EventTick_Happiness,
    EventTick_Hintsfile,
    EventTick_Hunger,
    EventTick_Interval,
    EventTick_Kind3,
    EventTick_Kind54,
    EventTick_Kind68,
    EventTick_Link,
    EventTick_Lookat,
    EventTick_Loopcomposite,
    EventTick_Message,
    EventTick_Need,
    EventTick_Needat,
    EventTick_Needgardeners,
    EventTick_Needin,
    EventTick_Needmechanics,
    EventTick_Parkvisitors,
    EventTick_Pathscenery,
    EventTick_Place,
    EventTick_Powerrides,
    EventTick_Purge,
    EventTick_Range,
    EventTick_Remove,
    EventTick_Removerange,
    EventTick_Report,
    EventTick_Ridecoverage,
    EventTick_Riders,
    EventTick_Ridevisitors,
    EventTick_Save,
    EventTick_Scenerycoverage,
    EventTick_Selectmode,
    EventTick_Selecttab,
    EventTick_Selecttheme,
    EventTick_Shopcoverage,
    EventTick_Studarea,
    EventTick_Take,
    EventTick_Techlevel,
    EventTick_Themeicon,
    EventTick_Totcoverage,
    EventTick_Unglue,
    EventTick_Workers,
    EventTick_Zoning,
};

/* ---- g_lowlevel_ai
 * call site: the low-level bloke AI states, blokemisc.c:107 / lowlevelai.c:607
 * type:      (i32) -> void  */
extern void LowAI_BounceTurn(void*);
extern void LowAI_FollowPath(void*);
extern void LowAI_SeekPath(void*);
extern void LowAI_Turn(void*);
extern void LowAI_Unimplemented(void*);
extern void LowAI_Wait(void*);
extern void LowAI_WaitForTile(void*);
extern void LowAI_WaitWhilePointed(void*);
extern void LowAI_WalkLine(void*);
extern void LowAI_WalkLineOnPath(void*);
extern void LowAI_WalkLineResume(void*);
extern void LowAI_WalkLineToPath(void*);
extern void LowAI_WalkToJunction(void*);
extern void LowAI_Wander(void*);
extern void LowAI_WorkerWalkLine(void*);
extern void LowAI_WorkerWander(void*);

typedef void (*ll_fn_g_lowlevel_ai)(void*);
ll_fn_g_lowlevel_ai const ll_tab_g_lowlevel_ai[] = {
    LowAI_BounceTurn,
    LowAI_FollowPath,
    LowAI_SeekPath,
    LowAI_Turn,
    LowAI_Unimplemented,
    LowAI_Wait,
    LowAI_WaitForTile,
    LowAI_WaitWhilePointed,
    LowAI_WalkLine,
    LowAI_WalkLineOnPath,
    LowAI_WalkLineResume,
    LowAI_WalkLineToPath,
    LowAI_WalkToJunction,
    LowAI_Wander,
    LowAI_WorkerWalkLine,
    LowAI_WorkerWander,
};

/* ---- g_level_db_sections
 * call site: the level-file keyword handlers, levelkw.c:937/956
 * type:      (i32, i32, i32) -> i32  */
extern int LevelKw_ADDBRICKS(void*, void*, void*);
extern int LevelKw_ADDFLAG(void*, void*, void*);
extern int LevelKw_AGES(void*, void*, void*);
extern int LevelKw_APPRAISAL(void*, void*, void*);
extern int LevelKw_BLUEPRINT(void*, void*, void*);
extern int LevelKw_BREIFINGFILE_BRIEFINGFILE(void*, void*, void*);
extern int LevelKw_BREIFINGFILE_BRIEFINGFILE(void*, void*, void*);
extern int LevelKw_BRIDGES(void*, void*, void*);
extern int LevelKw_CAPACITYCAP(void*, void*, void*);
extern int LevelKw_CAPACITYSCALE(void*, void*, void*);
extern int LevelKw_CHECKFLAG(void*, void*, void*);
extern int LevelKw_CLEAR(void*, void*, void*);
extern int LevelKw_CLEARAREA(void*, void*, void*);
extern int LevelKw_COMPOSITE(void*, void*, void*);
extern int LevelKw_CONNECT(void*, void*, void*);
extern int LevelKw_CURRENCY(void*, void*, void*);
extern int LevelKw_DEGRADE(void*, void*, void*);
extern int LevelKw_ENABLE(void*, void*, void*);
extern int LevelKw_END(void*, void*, void*);
extern int LevelKw_ENDLEVEL(void*, void*, void*);
extern int LevelKw_ENDSCREENS(void*, void*, void*);
extern int LevelKw_ENTRANCEFEE(void*, void*, void*);
extern int LevelKw_EXTENDPARK(void*, void*, void*);
extern int LevelKw_FEATURE(void*, void*, void*);
extern int LevelKw_FIXRIDES(void*, void*, void*);
extern int LevelKw_FLASHBUTTOFF(void*, void*, void*);
extern int LevelKw_FLASHBUTTON(void*, void*, void*);
extern int LevelKw_FMV(void*, void*, void*);
extern int LevelKw_FOODCOVERAGE(void*, void*, void*);
extern int LevelKw_FOREVER(void*, void*, void*);
extern int LevelKw_GARDENER(void*, void*, void*);
extern int LevelKw_GIVE(void*, void*, void*);
extern int LevelKw_GLUE(void*, void*, void*);
extern int LevelKw_HAPPINESS(void*, void*, void*);
extern int LevelKw_HAPPINESS_ENV(void*, void*, void*);
extern int LevelKw_HAP_FACTOR(void*, void*, void*);
extern int LevelKw_HINTSFILE(void*, void*, void*);
extern int LevelKw_HUNGER(void*, void*, void*);
extern int LevelKw_INIT(void*, void*, void*);
extern int LevelKw_INTERVAL(void*, void*, void*);
extern int LevelKw_INTRO(void*, void*, void*);
extern int LevelKw_LINK(void*, void*, void*);
extern int LevelKw_LOAD(void*, void*, void*);
extern int LevelKw_LOOKAT(void*, void*, void*);
extern int LevelKw_LOOPCOMPOSITE(void*, void*, void*);
extern int LevelKw_MAP(void*, void*, void*);
extern int LevelKw_MAXBLOKES(void*, void*, void*);
extern int LevelKw_MAXCAPACITY_MAXVISITORS(void*, void*, void*);
extern int LevelKw_MAXCAPACITY_MAXVISITORS(void*, void*, void*);
extern int LevelKw_MECHANIC(void*, void*, void*);
extern int LevelKw_MESSAGE(void*, void*, void*);
extern int LevelKw_MINCAPACITY_MINVISITORS(void*, void*, void*);
extern int LevelKw_MINCAPACITY_MINVISITORS(void*, void*, void*);
extern int LevelKw_NEED(void*, void*, void*);
extern int LevelKw_NEEDAT(void*, void*, void*);
extern int LevelKw_NEEDGARDENERS(void*, void*, void*);
extern int LevelKw_NEEDIN(void*, void*, void*);
extern int LevelKw_NEEDMECHANICS(void*, void*, void*);
extern int LevelKw_OBJECTIVE(void*, void*, void*);
extern int LevelKw_ONEOFF(void*, void*, void*);
extern int LevelKw_ONGOING(void*, void*, void*);
extern int LevelKw_PARKVISITORS(void*, void*, void*);
extern int LevelKw_PATHSCENERY(void*, void*, void*);
extern int LevelKw_PERMANENT(void*, void*, void*);
extern int LevelKw_PLACE(void*, void*, void*);
extern int LevelKw_POWERRIDES(void*, void*, void*);
extern int LevelKw_PROMPT(void*, void*, void*);
extern int LevelKw_PURGE(void*, void*, void*);
extern int LevelKw_RANGE(void*, void*, void*);
extern int LevelKw_REMINDER(void*, void*, void*);
extern int LevelKw_REMOVE(void*, void*, void*);
extern int LevelKw_REMOVERANGE(void*, void*, void*);
extern int LevelKw_REPORT(void*, void*, void*);
extern int LevelKw_RESEARCH(void*, void*, void*);
extern int LevelKw_REWARD(void*, void*, void*);
extern int LevelKw_RIDECOVERAGE(void*, void*, void*);
extern int LevelKw_RIDERS(void*, void*, void*);
extern int LevelKw_RIDEVISITORS(void*, void*, void*);
extern int LevelKw_SAVE(void*, void*, void*);
extern int LevelKw_SCENERYCOVERAGE(void*, void*, void*);
extern int LevelKw_SELECTMODE(void*, void*, void*);
extern int LevelKw_SELECTTAB(void*, void*, void*);
extern int LevelKw_SELECTTHEME(void*, void*, void*);
extern int LevelKw_SHOPCOVERAGE(void*, void*, void*);
extern int LevelKw_STUDAREA(void*, void*, void*);
extern int LevelKw_TAKE(void*, void*, void*);
extern int LevelKw_TECHLEVEL(void*, void*, void*);
extern int LevelKw_THEMEICON(void*, void*, void*);
extern int LevelKw_TOTCOVERAGE(void*, void*, void*);
extern int LevelKw_UNGLUE(void*, void*, void*);
extern int LevelKw_WORKERS(void*, void*, void*);
extern int LevelKw_ZONING(void*, void*, void*);
extern int LevelKw_none(void*, void*, void*);

typedef int (*ll_fn_g_level_db_sections)(void*, void*, void*);
ll_fn_g_level_db_sections const ll_tab_g_level_db_sections[] = {
    LevelKw_ADDBRICKS,
    LevelKw_ADDFLAG,
    LevelKw_AGES,
    LevelKw_APPRAISAL,
    LevelKw_BLUEPRINT,
    LevelKw_BREIFINGFILE_BRIEFINGFILE,
    LevelKw_BREIFINGFILE_BRIEFINGFILE,
    LevelKw_BRIDGES,
    LevelKw_CAPACITYCAP,
    LevelKw_CAPACITYSCALE,
    LevelKw_CHECKFLAG,
    LevelKw_CLEAR,
    LevelKw_CLEARAREA,
    LevelKw_COMPOSITE,
    LevelKw_CONNECT,
    LevelKw_CURRENCY,
    LevelKw_DEGRADE,
    LevelKw_ENABLE,
    LevelKw_END,
    LevelKw_ENDLEVEL,
    LevelKw_ENDSCREENS,
    LevelKw_ENTRANCEFEE,
    LevelKw_EXTENDPARK,
    LevelKw_FEATURE,
    LevelKw_FIXRIDES,
    LevelKw_FLASHBUTTOFF,
    LevelKw_FLASHBUTTON,
    LevelKw_FMV,
    LevelKw_FOODCOVERAGE,
    LevelKw_FOREVER,
    LevelKw_GARDENER,
    LevelKw_GIVE,
    LevelKw_GLUE,
    LevelKw_HAPPINESS,
    LevelKw_HAPPINESS_ENV,
    LevelKw_HAP_FACTOR,
    LevelKw_HINTSFILE,
    LevelKw_HUNGER,
    LevelKw_INIT,
    LevelKw_INTERVAL,
    LevelKw_INTRO,
    LevelKw_LINK,
    LevelKw_LOAD,
    LevelKw_LOOKAT,
    LevelKw_LOOPCOMPOSITE,
    LevelKw_MAP,
    LevelKw_MAXBLOKES,
    LevelKw_MAXCAPACITY_MAXVISITORS,
    LevelKw_MAXCAPACITY_MAXVISITORS,
    LevelKw_MECHANIC,
    LevelKw_MESSAGE,
    LevelKw_MINCAPACITY_MINVISITORS,
    LevelKw_MINCAPACITY_MINVISITORS,
    LevelKw_NEED,
    LevelKw_NEEDAT,
    LevelKw_NEEDGARDENERS,
    LevelKw_NEEDIN,
    LevelKw_NEEDMECHANICS,
    LevelKw_OBJECTIVE,
    LevelKw_ONEOFF,
    LevelKw_ONGOING,
    LevelKw_PARKVISITORS,
    LevelKw_PATHSCENERY,
    LevelKw_PERMANENT,
    LevelKw_PLACE,
    LevelKw_POWERRIDES,
    LevelKw_PROMPT,
    LevelKw_PURGE,
    LevelKw_RANGE,
    LevelKw_REMINDER,
    LevelKw_REMOVE,
    LevelKw_REMOVERANGE,
    LevelKw_REPORT,
    LevelKw_RESEARCH,
    LevelKw_REWARD,
    LevelKw_RIDECOVERAGE,
    LevelKw_RIDERS,
    LevelKw_RIDEVISITORS,
    LevelKw_SAVE,
    LevelKw_SCENERYCOVERAGE,
    LevelKw_SELECTMODE,
    LevelKw_SELECTTAB,
    LevelKw_SELECTTHEME,
    LevelKw_SHOPCOVERAGE,
    LevelKw_STUDAREA,
    LevelKw_TAKE,
    LevelKw_TECHLEVEL,
    LevelKw_THEMEICON,
    LevelKw_TOTCOVERAGE,
    LevelKw_UNGLUE,
    LevelKw_WORKERS,
    LevelKw_ZONING,
    LevelKw_none,
};
/* not named above, and why:
 *   g_str_none  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 *   g_str_purge  [a stale name no game TU defines: gen_link.py forwards it, and takes the forwarder's signature from the registering file's declaration]
 */

/* ---- g_car_class_vt
 * call site: the curve method table: every position / tangent / offset / up body, reached through coaster10.c:170/212 and coaster13.c:236
 * type:      (i32, f32, i32) -> void  */
extern void CoasterArc_GetPosRail0(void*, float, void*);
extern void CoasterArc_GetPosRail2(void*, float, void*);
extern void TrackCurve_ArcPosition(void*, float, void*);
extern void TrackCurve_ArcTangent(void*, float, void*);
extern void TrackCurve_CubicOffsetMinus(void*, float, void*);
extern void TrackCurve_CubicOffsetPlus(void*, float, void*);
extern void TrackCurve_CubicPosition(void*, float, void*);
extern void TrackCurve_CubicTangent(void*, float, void*);
extern void TrackCurve_CubicUpVector(void*, float, void*);
extern void TrackCurve_LineOffsetMinus(void*, float, void*);
extern void TrackCurve_LineOffsetPlus(void*, float, void*);
extern void TrackCurve_LinePosition(void*, float, void*);
extern void TrackCurve_LineTangent(void*, float, void*);
extern void TrackCurve_LineUpVector(void*, float, void*);
extern void TrackCurve_NormalAt(void*, float, void*);

typedef void (*ll_fn_g_car_class_vt)(void*, float, void*);
ll_fn_g_car_class_vt const ll_tab_g_car_class_vt[] = {
    CoasterArc_GetPosRail0,
    CoasterArc_GetPosRail2,
    TrackCurve_ArcPosition,
    TrackCurve_ArcTangent,
    TrackCurve_CubicOffsetMinus,
    TrackCurve_CubicOffsetPlus,
    TrackCurve_CubicPosition,
    TrackCurve_CubicTangent,
    TrackCurve_CubicUpVector,
    TrackCurve_LineOffsetMinus,
    TrackCurve_LineOffsetPlus,
    TrackCurve_LinePosition,
    TrackCurve_LineTangent,
    TrackCurve_LineUpVector,
    TrackCurve_NormalAt,
};
/* not named above, and why:
 *   TrackCurve_GatherParams  [(i32, i32) -> i32]
 *   TrackCurve_GetLimits  [(i32, i32) -> i32]
 *   TrackCurve_GetQuarterTurnSamples  [(i32, i32) -> i32]
 */

/* The number of (slot, body) pairs this file type-checks. Touching every
 * table keeps the compiler from discarding them unread. */
int ll_callback_type_pairs(void)
{
    int n = 0;
    n += (int)(sizeof ll_tab_cb_90 / sizeof ll_tab_cb_90[0]);
    n += (int)(sizeof ll_tab_cb_94 / sizeof ll_tab_cb_94[0]);
    n += (int)(sizeof ll_tab_cb_remove / sizeof ll_tab_cb_remove[0]);
    n += (int)(sizeof ll_tab_cb_a0 / sizeof ll_tab_cb_a0[0]);
    n += (int)(sizeof ll_tab_cb_a4 / sizeof ll_tab_cb_a4[0]);
    n += (int)(sizeof ll_tab_cb_a8 / sizeof ll_tab_cb_a8[0]);
    n += (int)(sizeof ll_tab_cb_ac / sizeof ll_tab_cb_ac[0]);
    n += (int)(sizeof ll_tab_cb_load / sizeof ll_tab_cb_load[0]);
    n += (int)(sizeof ll_tab_cb_c0 / sizeof ll_tab_cb_c0[0]);
    n += (int)(sizeof ll_tab_input / sizeof ll_tab_input[0]);
    n += (int)(sizeof ll_tab_render / sizeof ll_tab_render[0]);
    n += (int)(sizeof ll_tab_g_event_tick / sizeof ll_tab_g_event_tick[0]);
    n += (int)(sizeof ll_tab_g_lowlevel_ai / sizeof ll_tab_g_lowlevel_ai[0]);
    n += (int)(sizeof ll_tab_g_level_db_sections / sizeof ll_tab_g_level_db_sections[0]);
    n += (int)(sizeof ll_tab_g_car_class_vt / sizeof ll_tab_g_car_class_vt[0]);
    return n;
}
