/* install_paths -- ll_host_resolve_path over a PRELOADED MEMFS.  Scope PORT-A3.
 *
 * `ll_host_resolve_path` (portable/src/hostwin/kernel32.c) is what makes the
 * paths the game wrote for a 1999 Windows install resolve on a modern host: the
 * emulated `D:` drive, backslashes, each component matched case-insensitively,
 * and -- when a directory component does not exist at all -- the last component
 * looked for in the deepest directory that did match, which is what makes the
 * flat `gamedata/main` serve ".\strings\stab.str".
 *
 * It had no test, and on THIS machine it could not have had a useful one: every
 * other node target uses `-sNODERAWFS=1`, which goes straight to APFS, and APFS
 * is case-insensitive by default, so `stat("LEGOLAND.ICM")` succeeds on the
 * first try and the case-folding code never runs. Measured: `ls
 * gamedata/main/LEGOLAND.ICM` lists `Legoland.icm`. The browser is the opposite
 * case and the one that matters -- a preloaded MEMFS is case-SENSITIVE whatever
 * the machine that packaged it -- and so is Linux CI on ext4.
 *
 * So this target is linked WITHOUT NODERAWFS and with `--preload-file`, which
 * is exactly the browser's filesystem, and it runs under node. The fixture is
 * generated by cmake/headless.cmake from nothing: empty files whose NAMES mirror
 * the real install's mixed case. No game asset is involved, so it runs with or
 * without gamedata/.
 *
 * The fixture (cmake/headless.cmake keeps this list):
 *
 *   /gamedata/Legoland.icm      the real install's case; asked for as LEGOLAND.ICM
 *   /gamedata/stab.str          lower case; asked for as ".\strings\Stab.str"
 *   /gamedata/Graphics/Erase It.lls   a real subdirectory, mixed case, a space
 *   /cd/Legoland.res            the emulated D: drive ($LL_CD_DIR)
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>

#include "ll_host.h"

static int checks, fails;

/* A leading "./" is not part of the answer. `ll_resolve_inplace` returns a path
 * that already stats UNCHANGED -- which is right, it opens -- so ".\x" comes
 * back as "./x" and ".\strings\x" as "./strings/x" while "LEGOLAND.ICM",
 * which does not stat, is rewritten to "Legoland.icm". What the callers need is
 * a path that opens the intended file, so the comparison below ignores the
 * prefix rather than pinning a normalisation nobody depends on. */
static const char* strip_dot(const char* p)
{
    return (p[0] == '.' && p[1] == '/') ? p + 2 : p;
}

static void pass(const char* what)
{
    printf("ok       %s\n", what);
    checks++;
}

static void fail(const char* what, const char* got, const char* want)
{
    printf("FAIL     %s: got \"%s\", want \"%s\"\n", what, got, want);
    checks++;
    fails++;
}

/* `in` must resolve to `want`, and the result must be openable: a resolver that
 * returns a plausible string nothing can open is the failure mode to catch. */
static void resolves(const char* in, const char* want)
{
    char path[1024];
    char what[1200];
    int  fd;

    snprintf(what, sizeof what, "\"%s\" -> \"%s\"", in, want);
    ll_host_resolve_path(path, sizeof path, in, 0);
    if (strcmp(strip_dot(path), want) != 0) {
        fail(what, path, want);
        return;
    }
    fd = open(path, O_RDONLY);
    if (fd < 0) {
        fail(what, "resolved but will not open", want);
        return;
    }
    close(fd);
    pass(what);
}

/* A path with no file behind it must come back NORMALISED and unresolved, not
 * silently pointed at something else: the loaders test the open, and the
 * missing-directory fallback must not be able to invent a hit. */
static void unresolved(const char* in, const char* want)
{
    char path[1024];
    char what[1200];

    snprintf(what, sizeof what, "\"%s\" stays \"%s\" (nothing to find)", in, want);
    ll_host_resolve_path(path, sizeof path, in, 0);
    if (strcmp(strip_dot(path), want) == 0)
        pass(what);
    else
        fail(what, path, want);
}

int main(void)
{
    char path[1024];

    /* $LL_CD_DIR, set the way the BROWSER has to set it. Emscripten seeds its
     * environment from the host's `process.env` only under NODERAWFS; a MEMFS
     * build's getenv sees almost nothing, so a page cannot be told the CD
     * directory through the environment and must set it itself. PORT-B's
     * src/browser/main.c already does exactly this
     * (`setenv("LL_CD_DIR", LL_GAMEDATA "/volumes", 0)`), which is why the page
     * finds the volumes; this test would silently skip every D: case if it
     * relied on ctest's ENVIRONMENT property instead. */
    setenv("LL_CD_DIR", "/cd", 1);

    if (chdir("/gamedata") != 0) {
        printf("FAIL     chdir /gamedata: the preload did not mount\n");
        return 1;
    }
    printf("== install_paths: ll_host_resolve_path over a preloaded MEMFS"
           " (case-sensitive)\n");

    /* The case-sensitivity this test exists for: prove MEMFS really is case
     * sensitive here, so a pass below means the resolver did the work rather
     * than the filesystem doing it by accident. */
    checks++;
    if (open("LEGOLAND.ICM", O_RDONLY) < 0)
        pass("MEMFS is case-sensitive: open(\"LEGOLAND.ICM\") fails");
    else
        fail("MEMFS is case-sensitive: open(\"LEGOLAND.ICM\") fails",
             "it opened", "ENOENT");

    /* 1. exact, and the `.\` prefix the game writes. */
    resolves("Legoland.icm", "Legoland.icm");
    resolves(".\\Legoland.icm", "Legoland.icm");

    /* 2. CASE. LEGOLAND.ICM is how data2.c asks for it (docs/runtime/assets.md,
     *    and PORT-C finding: LEGOLAND.ICM vs Legoland.icm). */
    resolves("LEGOLAND.ICM", "Legoland.icm");
    resolves("legoland.icm", "Legoland.icm");
    resolves(".\\LEGOLAND.ICM", "Legoland.icm");

    /* 3. A real subdirectory, the wrong case in BOTH components, and a space in
     *    the name (every sprite the front end loads has one). */
    resolves(".\\graphics\\erase it.lls", "Graphics/Erase It.lls");
    resolves(".\\GRAPHICS\\ERASE IT.LLS", "Graphics/Erase It.lls");

    /* 4. LAYOUT: a directory component that does not exist at all. The install
     *    had .\strings\; gamedata/main is flat. This is what LoadStrings needs,
     *    and LoadStrings is `if (!f) exit(1)`. */
    resolves(".\\strings\\stab.str", "stab.str");
    resolves(".\\strings\\Stab.str", "stab.str");
    resolves(".\\STRINGS\\STAB.STR", "stab.str");

    /* 5. The emulated CD drive, $LL_CD_DIR. RES_OpenVolume asks for
     *    "D:\Legoland.res" once the probe has settled on a drive letter. */
    resolves("D:\\Legoland.res", "/cd/Legoland.res");
    resolves("D:\\LEGOLAND.RES", "/cd/Legoland.res");
    resolves("d:\\legoland.res", "/cd/Legoland.res");

    /* 6. Nothing there: normalised, not invented. */
    unresolved("NoSuchFile.dat", "NoSuchFile.dat");
    unresolved(".\\strings\\nosuch.str", "strings/nosuch.str");
    unresolved("D:\\NoSuchVolume.res", "/cd/NoSuchVolume.res");

    /* 7. `create` is the plain normalisation: a path being written must not be
     *    rewritten to something that already exists. */
    ll_host_resolve_path(path, sizeof path, ".\\save\\NEWGAME.SAV", 1);
    checks++;
    if (strcmp(strip_dot(path), "save/NEWGAME.SAV") == 0)
        pass("create=1 normalises only: \".\\save\\NEWGAME.SAV\" -> \"save/NEWGAME.SAV\"");
    else
        fail("create=1 normalises only", path, "save/NEWGAME.SAV");

    printf("== install_paths: %d checks, %d failed\n", checks, fails);
    return fails ? 1 : 0;
}
